[
    {
      "lectureNumber": 1,
      "lectureName": "Vector & Calculus 12 : Components of ...",
      "lectureCode": "012ee85e-59d9-40af-ade3-cc40a4650290",
      "classNotesCode": "31f4ee6f-603a-4c26-b129-e9bc49a216da.pdf",
      "dppsPdfCode": "48740536-c33e-4146-aec2-e458b60d51bd.pdf",
      "dppsSolutionCode": "c3e56c95-1573-4914-a8c3-d4fb8ffada72"
    },
    {
      "lectureNumber": 2,
      "lectureName": "Vector & Calculus 11 : Angle between ...",
      "lectureCode": "704ffad1-6cec-4155-b40f-fb34d21c9a05",
      "classNotesCode": "16b85b7b-09d5-44e9-8110-556a2bd6e3f4.pdf",
      "dppsPdfCode": "c35d404d-cbff-4884-a022-d1d9d1dd3a6e.pdf",
      "dppsSolutionCode": "2561e370-bf94-44ba-a359-b84d97ad178b"
    },
    {
      "lectureNumber": 3,
      "lectureName": "Vector & Calculus 10 : Question Pract...",
      "lectureCode": "9a58c23b-ee04-4ff1-b8b3-5ee31b2cf44b",
      "classNotesCode": "48b0a3e0-fb95-49ef-b1ac-82da7417054c.pdf",
      "dppsPdfCode": "2cbb1a5e-9f82-418b-9e4b-95b67fb28dbd.pdf",
      "dppsSolutionCode": "437bff10-29da-41ae-84b3-3e59ed2ac95b"
    },
    {
      "lectureNumber": 4,
      "lectureName": "Vector & Calculus 09 : Question Pract...",
      "lectureCode": "573404e6-355e-41b6-90c8-dd98722b108c",
      "classNotesCode": "64db9f18-5560-4233-80ef-63f9480d469b.pdf",
      "dppsPdfCode": "6a4b233c-1627-4108-83ff-4344263ea9f7.pdf",
      "dppsSolutionCode": "c0dd8319-18b6-4348-8db7-dd15f3ef0937"
    },
    {
      "lectureNumber": 5,
      "lectureName": "Vector & Calculus 08 : Unit Vector ||...",
      "lectureCode": "d420c59b-cfa3-4f8d-bd74-715785245da5",
      "classNotesCode": "9d5a112d-4ec9-4967-9383-a306f641b121.pdf",
      "dppsPdfCode": "39eb1f08-7780-4624-b59b-e281602ffc89.pdf",
      "dppsSolutionCode": ""
    },
    {
      "lectureNumber": 6,
      "lectureName": "Vector & Calculus 07 : Subtraction Of...",
      "lectureCode": "b63741b5-f06e-45b1-b21e-1acacb257c11",
      "classNotesCode": "97bc3ad9-7e74-4437-bab2-e849f16a7651.pdf",
      "dppsPdfCode": "be9bd319-ca85-4071-aca8-f8fb246276d4.pdf",
      "dppsSolutionCode": ""
    },
    {
      "lectureNumber": 7,
      "lectureName": "Vector & Calculus 06 : Question Pract...",
      "lectureCode": "d75cd805-1fc7-4f9e-b973-7505f36fcc2a",
      "classNotesCode": "aede4046-99e7-4415-bf0f-f22541033911.pdf",
      "dppsPdfCode": "4dbcbd7b-84cd-4b13-9d49-768294c43931.pdf",
      "dppsSolutionCode": ""
    },
    {
      "lectureNumber": 8,
      "lectureName": "Vector & Calculus 05 : Question Pract...",
      "lectureCode": "bbe3024a-d12c-45f1-bae3-0e5d7786b241",
      "classNotesCode": "4ef826c1-50d2-4234-861f-b54632b59a75.pdf",
      "dppsPdfCode": "8a264c99-ee74-493a-a4d3-e82f326057f5.pdf",
      "dppsSolutionCode": ""
    },
    {
      "lectureNumber": 9,
      "lectureName": "Vector & Calculus 04 : Question on tr...",
      "lectureCode": "90ecbb60-22c3-4e59-ab40-f14685f2939f",
      "classNotesCode": "bb7d7e33-1951-4603-841a-8c1134a32fa7.pdf",
      "dppsPdfCode": "85271398-2178-48d3-83e4-62939e9eba78.pdf",
      "dppsSolutionCode": ""
    },
    {
      "lectureNumber": 10,
      "lectureName": "Vector & Calculus 03 : Angle between ...",
      "lectureCode": "7c4c4787-637c-43e4-8309-8c9e4a87feeb",
      "classNotesCode": "d041792e-883b-404e-a46d-b3ad9e049ebc.pdf",
      "dppsPdfCode": "b304c6c8-07cb-4881-88e8-9f7b6308b559.pdf",
      "dppsSolutionCode": ""
    },
    {
      "lectureNumber": 11,
      "lectureName": "Vector & Calculus 02 : Types of Vecto...",
      "lectureCode": "881f3b5a-f70d-4d73-b44d-3c2455081112",
      "classNotesCode": "f367740b-9530-4cb2-94c1-15fd1adeabea.pdf",
      "dppsPdfCode": "72d1702b-9d28-47e1-aa00-f8d1ed33379b.pdf",
      "dppsSolutionCode": ""
    },
    {
      "lectureNumber": 12,
      "lectureName": "Vector & Calculus 01 : Quadratic Equa...",
      "lectureCode": "a9b5d865-fbfe-4e90-b9dc-ce73b6ab9a2c",
      "classNotesCode": "6bf0fecc-bb1c-4531-829a-f238e7970643.pdf",
      "dppsPdfCode": "cd96979a-6739-4a8c-bc53-2255ed3da232.pdf",
      "dppsSolutionCode": ""
    }
  ] 
  